#!/system/xbin/bash
echo "请把脚本放在系统英文目录下"
sleep 1
DIR=/sdcard/baidu
basepath=$(cd `dirname $0`; pwd -P)
echo "当前路径为：$basepath"
echo -n "请输入你要读取的文件夹路径："
read Input
if [ "$Input" == "" ];then
echo "默认为当前路径：$basepath"
cd $basepath
else
echo "你输入的文件夹路径为$Input"
cd $Input
fi
echo -n "请输入你要将数据输出保存的文件路径"
echo "默认路径为：$DIR"
read Output
if [ "$Output" == "" ];then
echo "默认为路径：$DIR"
Outdir=$DIR
else
Outdir=$Output
echo "输出保存的文件路径为$Output"
fi
rm -rf $Outdir/en2.txt &> /dev/null
for file in `ls $basepath`;do
   echo "$file" >> $Outdir/en2.txt
done
sed -i 's/.*/& 60000/' $Outdir/en2.txt 
echo "制作完成，请到$DIR复制黏贴到$Outdir/baidu/en2.txt后"

 

