#!/system/xbin/bash
SOURCE=$1
TARGET=$2
#CP=./fack_cp
CP=cp
if [ ! -e $SOURCE ] || [ ! -e $TARGET ];then
echo "用法错误，自动退出！"
sleep 1
exit
fi
$CP "$SOURCE" "$TARGET" &
CPID=$!
isalive()
{
out=`ps -p $1 2> /dev/null`
return $?
}
while [ 1 ]; do
{
SSIZE=`ls -l $SOURCE | awk "{print \\\$5}"`
if [ -f $TARGET ]; then
TSIZE=`ls -l $TARGET | awk "{print \\\$5}"`
else
TSIZE="0"
fi
PERCENT=`echo "scale=2; $TSIZE/$SSIZE*100" | bc -l`
RATE=`echo "scale=0; 63*$PERCENT/100" | bc -l`
BLUE="\\033[3;44m"
NORMAIL="\\033[0;39m"
BAR=$BLUE
i=0
while [ $i -le 62 ]; do
[ $i = $RATE ] && BAR=$BAR"\\033[7;39m"
BAR=$BAR" "
let i=$i+1
done
BAR=$BAR$NORMAIL
echo -en "\r$BAR ${PERCENT}%"
if ! isalive "$CPID"; then echo -en "\n"; exit; fi
sleep 1
}
done