#!/system/xbin/bash
source exfunction
clear
cd $AB
echo "-1- :dex2jar生成jar "
echo
echo "-2- :jardex生成dex文件"
echo
echo "-0- :退出/回车"
echo
read -n1 -p "请选择操作类型：" jar
clear
[ -z $jar ] && exit
if [ "$jar" == "1" ] ;then
###############
PWD=`'pwd'`
    cd $PWD
#从第三方脚本调用直接到呼起目录
#文件类型在父脚本设置例子apk
#filetype=apk设置主
    grep_cmd=`find . | grep .apk$ | sort -f`
     grep_cmd=`echo $grep_cmd | sed -e 's/\.\///g'`
echo " 获取到可用文件："
    count=0
    $ bb rm -f ../temp.list &> $null
    for filename in $grep_cmd 
    do
      count=$(($count+1))
      # Store file names in an array
      file_array[$count]=$filename
      file_to_sign[$count]=0
   Size=`Filesize0 $filename`
      echo "  ($count). $filename" $Size >> ../temp.list
    done
    $bb more ../temp.list
    $bb rm -f ../temp.list &> $null
#已经获取得到文件列表参数
    read -n1 -p " 请输入文件编号(0=取消):" enterNumbers
    echo
clear
    if [ "$enterNumbers" == "0" ] || [ "$enterNumbers" == "" ]
    then
   test
    else 
      for num in $enterNumbers
      do
        num_start=$num
        num_end=$num
        num_start=`echo $num | sed 's/\([0-9]*\)-[0-9]*/\1/'`
        num_end=`echo $num | sed 's/[0-9]*-\([0-9]*\)/\1/'`
        if [ "$num_start" == "" ] || [ "`echo $num_start | sed 's/[0-9]*//'`" != "" ]
        then
          echo " 提醒: 错误输入('$num' 不是一个有效的数字或范围)"
          test
        fi

         if [ "$num_end" == "" ] || [ "`echo $num_end | sed 's/[0-9]*//'`" != "" ]
        then
          echo " 提醒: 错误输入('$num' 不是一个有效的数字或范围)"
          test
        fi

        if [ $num_end -lt $num_start ]
        then
          echo " 提醒: 错误输入($num_start 不能少于 $num_end)"
          test
        fi

        
        #
        # 指定被选定的文件
        #

        for (( i=$num_start; i<=$num_end; i++ ))
        do
      
          if [ "${file_array[$i]}" == "" ]
          then
            echo " 提醒: 没有文件在 #$i"
            continue
          else
            file_to_sign[$i]=1
          fi

        done

      done

      #
      # 通过排列并签署相应的文件
      #
      for (( i=1; i<=$count; i++ ))
      do

        if [ "${file_to_sign[$i]}" == "1" ]
        then
export chosen=""${file_array[$i]}""
        fi
      done
echo "编译$chosen"
    fi

###############
       if [ "$chosen" != "" ] ;then
echo 反编译$name_file
else
echo "错误: 没有输入 $name_file 文件"
busybox sleep 3
exit 0
fi
echo "正在对$chosen进行dex2jar操作"
echo "....... $chosen"
d2j-dex2jar $chosen

filename=`echo $chosen | sed 's/.apk//'`
#filename=`echo $filename | sed -e 's/\.\///g'`

class_file=$filename'-dex2jar'.jar
if [ -f $class_file ] ;then
       echo "成功对$name_file生成$class_file"
echo "请到$AB目录修改$class_file"
read -t5 -p "按回车键退出..."
exit
else
echo "错误无法对$name_file进行dex2jar"
read -t5 -p "按回车键退出..."
exit
fi
fi
if [ "$jar" == "2" ] ;then
       jardex2
fi
if [ $jar == 0 ] ;then
       echo 退出中 && exit 1
fi
