#!/system/xbin/bash
source exfunction
#程序员专用版
clear
echo 
tool_dir=$tool
test=$exboot/test
read -p "请输入sh文件所在目录:" shdir
shdir=${shdir:-"$test"}
echo "输入目录为"
echo " $shdir"
sleep 1
 if [ ! -e $shdir ];then
echo " $shdir不存在，请重新输入"
sleep 1
exit
 fi
cd $shdir
sh_filename=`find . | grep -i \\.sh$ | sort -f`
sh_too_filename=`find . | grep -i \\[0-9].sh$ | sort -f`
filename=`echo $sh_filename | sed -e 's/\.\///g'`

#Linker
while :
do
clear
echo "   ==============================="
echo "             文件加密工具"
echo "   ==============================="
echo
echo " -1- 单个sh加密"
echo
echo " -2- 批量sh加密"
echo
echo " -3- 解密 sh"
echo
read -n1 -p "请选择: " encrypt
clear
      [ -z $encrypt ]  && exit

        if [ "$encrypt" == "1" ]
        then
        cd $shdir

   if [ "$sh_filename" == "" ]
   then
     echo "错误未发现$sh_filename文件"
     read -t3 -p "按回车键继续"
     exit 1
   fi

 
IFS=$'\n'
i=1
#file_array[0]="取消"
for a in `ls *.sh`;do
    if [ -f $a ];then
        file_array[$i]="$a"
        i=$((i+1))
    fi
done
echo "所有可用文件："
echo
for ((i=1;i<="${#file_array[@]}";i++));do
Size=`Filesize0 ${file_array[$i]}`
    echo " (${i}). ${file_array[$i]}"  $Size
done
IFS=$' \t\n'

echo
read -n1 -p "请输入文件序号: " enterNumber

if [ "$enterNumber" == "0" ] || [ -z $enterNumber ]
then
  exit 

# 验证输入是一个数字
elif [ "`echo $enterNumber | sed 's/[0-9]*//'`" == "" ]
then
 file_chosen=${file_array[$enterNumber]}
  file=$file_chosen
  name=${file%.*}

  if [ "$file_chosen" == "" ]
  then
    cd ..
    exit 0
  fi
   echo "开始对$file_chosen进行加密操作" 
#shcx=`cc=-static shc -r -v -f "$@"`
shcx $file_chosen 

#验证是否加密成功
 if [ -f $file_chosen.x ]
 then
 echo "恭喜加密成功!"
$bb rm -r $file_chosen.x.c
mv $file_chosen.x $name
#$bb rm -rf $file_chosen
 else
 echo "哎呀加密失败了."
 read -t3 -p "按回车键继续..."
 exit
 fi
echo "= = = = = = = = "
Filesize $name
echo "= = = = = = = = "
   echo "请到$shdir目录下提取文件"
   read -t6 -p "按回车键退出..."
   exit
        fi
encrypt
fi

        if [ "$encrypt" == "2" ]
        then
        alljiami
        fi

        if [ "$encrypt" == "3" ]
        then
cd $shdir
Xzfile sh

       unshc $file
read
        fi
        

        
done
